### ISSUE TITLE
Erro no uso do docker-compose

### ISSUE THREAD

**Issue by airlonfilho** [aurelianosza/api-livros#1]
**Ao tentar usar o docker-compose está dando o seguinte erro:**

```
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
Você poderia me ajudar a solucionar esse problema?

**Comment by aurelianosza** [comment]
Aqui estão alguns fatores que podem fazer esse erro acontecer.

- Adicionar o docker ao grupo de usuário.
Para solucionar nesse caso, basta utilizar o comando no terminal **sudo usermod -a -G docker $USER**.

- O serviço do docker network não está sendo iniciado.
Para solucionar, basta setar a opção enable no serviço do docker **sudo systemctl enable docker**

- Variável de ambiente está com valor NULL no sistema operacional.
Uma solução seria exportar a variávle com o comando **export DOCKER_HOST=127.0.0.1**

Caso nenhuma dessas soluções o atenda, posso achar um tempo para ver o caso de seu sistema.

**Comment by airlonfilho** [comment]
Consegui resolver o problema desinstalando o docker e instalei seguindo a documentação do mesmo.
